### ISSUE TITLE
helloworld 代码问题

### ISSUE THREAD

**Issue by zzusunjs** [beiduofeng/learnVue3#2]
1.  class "preson" 中有错别字，而且类名应当描述组件的特质，不能随便写，比如这里可以叫做 msg-box，类名有多个单词组成的，一般用中划线分隔。
2. script 用都统一用 setup 属性的形式，可以简化代码
3. 不必要用的代码可以不写，比如这里其实没有用到 ref 的特性，‘hello world’ 字符串也从未被修改过，应该是一个简单的 const 变量

**Comment by beiduofeng** [comment]
ok
