### ISSUE TITLE
toRefs 代码问题

### ISSUE THREAD

**Issue by zzusunjs** [beiduofeng/learnVue3#3]
1. toRefs 这种稍显复杂的用法，最好是把官方的参考文档链接贴出来，写到注释里面，这种注释一般可以这样写：
// reference: https://cn.vuejs.org/api/reactivity-utilities.html#torefs

reference 就是参考文献，参考文档的意思。

2.  展示 ref 的基本用法这句话，可以单独放到 markdown 文档里面。另外，这个例子主要是展示了 toRefs 的用法才对，不是 ref 的基本用法。

3. 这个例子的代码还是比较复杂的，至少有 ref reactive toRefs 三个 api 的用法，建议增加单独的 ref 变量，比如 refName, 然后直接修改 ref 变量，对比看效果。

**Comment by beiduofeng** [comment]
OK
