### ISSUE TITLE
代码高亮组件添加功能：展示代码文件名

### ISSUE THREAD

**Issue by zzusunjs** [beiduofeng/learnVue3#6]
修改代码，通过 props 传入代码文件名，并在 CodeWrapper 组件中展示出来。

![image](https://github.com/user-attachments/assets/0e3f180c-e827-4759-8009-13c0d52f9f42)

@beiduofeng

**Comment by beiduofeng** [comment]
![image](https://github.com/user-attachments/assets/b16bf0a9-f139-44f4-a1a3-b9396037b0ec)
已完成
